site_name: Inteligência Artificial 2022/2
repo_url: https://github.com/fbarth/introduction_ai/
repo_name: Inteligência Artificial
site_url: https://fbarth.github.io/introduction_ai/

theme:
    name: 'material'

extra_css:
  - css/custom.css

nav:
  - 'Home': 'index.md'
  - 'Plano de Aula': 'plano_aula.md'
  - 'Ementa': 'ementa.md'
  - 'Aulas':
    - 'aulas/01_introducao_ia/introducao_ia.md'
    - 'aulas/02_agentes_autonomos/agentes_autonomos.md'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js

markdown_extensions:
  - attr_list
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: "docs/_snippets"
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: 
  - git-revision-date-localized
